Repository hmcts/aac-manage-case-assignment, pull requests merged in 2021-12, with the labels that each got.

#344 CCD-2312: Temporarily disable Fortify Scan in nightly build
  Jenkinsfile_nightly
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-344

#345 update log4j version
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-345

#346 Fix functional tests in master build
  src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201 - Assign Access within Organisation.feature
  src/functionalTest/resources/features/F-202 - Get Assignments in My Organisation/F-202 - Get Assignments in My Organisation.feature
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203 - Unassign Access Within Organisation.feature
  src/functionalTest/resources/features/F-206 - Request Notice Of Change/F-206 - Request Notice Of Change.feature
  src/functionalTest/resources/features/F-207 - Check Notice Of Change Approval/F-207 - Check Notice Of Change Approval.feature
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-346

#348 Ignore failing tests in master build
  src/functionalTest/resources/features/F-205 - Validate NoC Questions/F-205.feature
  src/functionalTest/resources/features/F-206 - Request Notice Of Change/F-206 - Request Notice Of Change.feature
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-348

#347 CCD-2351: Update log4j version to 2.16.0
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-347

#349 CCD-2231-update-cve-suppression-dates-dec-2021
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-349

#350 CCD-2374: Update log4j version to 2.17.0
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-350
