Repository hmcts/aac-manage-case-assignment, pull requests merged in 2021-05, with the labels that each got.

#281 RDM-9765 Added jit pack & befta code changes
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-281

#271 ACA-147 Update Assign access - switch from system to invoking user
  build.gradle
  src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201 - Assign Access within Organisation.feature
  src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201-Base-useUserToken.td.json
  src/functionalTest/resources/features/F-201 - Assign Access within Organisation/S-201.1b.td.json
  src/functionalTest/resources/features/F-201 - Assign Access within Organisation/S-201.2b.td.json
  src/integrationTest/java/uk/gov/hmcts/reform/managecase/fixtures/WiremockFixtures.java
  src/main/java/uk/gov/hmcts/reform/managecase/api/controller/CaseAssignmentController.java
  src/main/java/uk/gov/hmcts/reform/managecase/client/datastore/DataStoreApiClient.java
  src/main/java/uk/gov/hmcts/reform/managecase/repository/DataStoreRepository.java
  src/main/java/uk/gov/hmcts/reform/managecase/repository/DefaultDataStoreRepository.java
  src/main/java/uk/gov/hmcts/reform/managecase/service/CaseAssignmentService.java
  src/main/java/uk/gov/hmcts/reform/managecase/service/noc/NoticeOfChangeQuestions.java
  src/main/java/uk/gov/hmcts/reform/managecase/service/noc/RequestNoticeOfChangeService.java
  src/test/java/uk/gov/hmcts/reform/managecase/api/controller/CaseAssignmentControllerTest.java
  src/test/java/uk/gov/hmcts/reform/managecase/repository/DataStoreRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/managecase/service/CaseAssignmentServiceTest.java
  src/test/java/uk/gov/hmcts/reform/managecase/service/noc/NoticeOfChangeQuestionsTest.java
  src/test/java/uk/gov/hmcts/reform/managecase/service/noc/RequestNoticeOfChangeServiceTest.java
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-271

#295 CCD-1219 : Updated CVE suppress until date by 1 month
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-295
