Repository hmcts/aac-manage-case-assignment, pull requests merged in 2021-09, with the labels that each got.

#330 Ccd 1855 CVE 2021 22119
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-330

#331 CCD-1851: Resolve CVE-2021-28170
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-331

#333 add azuread version
  infrastructure/state.tf
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-333

#335 Updated CVE suppression dates to 25/10/2021
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-335
