Repository hmcts/aac-manage-case-assignment, pull requests merged in 2021-07, with the labels that each got.

#314 Fix 2 actionable CVEs
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-314

#315 CCD-1608 : Fortify Scan implementation for aac-manage-case-assignment
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-315

#316 CCD-1330: Updated CVE suppression dates to 25/08/2021
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-316

#318 RDM-12423 Improve Grant Assign Access FTAs
  config/owasp/suppressions.xml
  src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201 - Assign Access within Organisation.feature
  src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201_Case_Found.td.json
  src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201_Case_Not_Found.td.json
  src/functionalTest/resources/features/common/data-store/Case_Creation.td.json
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-318

#319 RDM-11550 Functional tests for Revoke Case Access API
  src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201_Case_Found.td.json
  src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201_Case_Not_Found.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203 - Unassign Access Within Organisation.feature
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C1_Case_Found_Becky.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C1_Case_Found_Benjamin.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C1_Case_Found_Bill.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C1_Case_Not_Found_Becky.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C1_Case_Not_Found_Benjamin.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C1_Case_Not_Found_Bill.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C2_Case_Found_Becky.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C2_Case_Found_Benjamin.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C2_Case_Found_Bill.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C2_Case_Not_Found_Becky.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C2_Case_Not_Found_Benjamin.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C2_Case_Not_Found_Bill.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C3_Case_Found_Becky.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C3_Case_Found_Benjamin.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C3_Case_Found_Bill.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C3_Case_Not_Found_Becky.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C3_Case_Not_Found_Benjamin.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_C3_Case_Not_Found_Bill.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_Separate_Org_Policies_Case_Found_Benjamin.td.json
  src/functionalTest/resources/features/common/response/Case_Found.td.json
  src/functionalTest/resources/features/common/response/Case_Not_Found.td.json
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-319
