Repository hmcts/aac-manage-case-assignment, pull requests merged in 2021-08, with the labels that each got.

#329 Added suppression entries for three CVEs
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-329

#326 Updated CVE suppression dates to 25/09/2021.
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-326

#328 Update Chart.yaml Java -> 3.6.0
  charts/aac-manage-case-assignment/Chart.yaml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-328
