Repository hmcts/aac-manage-case-assignment, pull requests merged in 2022-01, with the labels that each got.

#342 implemented retry pattern to prd to handle empty response
  build.gradle
  src/main/java/uk/gov/hmcts/reform/managecase/api/errorhandling/RestExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/managecase/client/datastore/DataStoreApiClientConfig.java
  src/main/java/uk/gov/hmcts/reform/managecase/client/definitionstore/DefinitionStoreApiClientConfig.java
  src/main/java/uk/gov/hmcts/reform/managecase/client/prd/PrdApiClientConfig.java
  src/main/java/uk/gov/hmcts/reform/managecase/client/prd/PrdFeignClient.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/managecase/api/controller/NoticeOfChangeControllerTest.java
  src/test/java/uk/gov/hmcts/reform/managecase/client/prd/PrdFeignClientTest.java
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-342

#353 Amending suppression dates by 1 month
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-353

#352 CCD-2378: Re-enable Fortify scan
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-352
