Repository hmcts/aac-manage-case-assignment, pull requests merged in 2022-05, with the labels that each got.

#384 CCD-3066: Add civil_service in authorised services for preview env
  charts/aac-manage-case-assignment/values.preview.template.yaml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-384

#385 CVE-2022-22968 : aac-manage-case-assignment fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-385

#387 CVE-2022-25647 : suppression change
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-387

#389 suppression of CVE-2016-1000027 and until date extension for current …
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-389

#391 suppression of CVE-2022-22970,CVE-2022-22971
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-391

#394 CVE-2022-29885: aac-manage-case-assignment fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-394

#393 Removed suppressions and updated spring-framework.version to 5.3.20
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-393
