Repository hmcts/aac-manage-case-assignment, pull requests merged in 2022-11, with the labels that each got.

#445 CCD-3917 CVE-2022-31690, CVE-2022-31690 CCD-3918 CVE-2022-42252 Suppr…
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-445

#442 CCD-3802 Update to fortify-client version
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-442

#443 CCD-3734 Update validation in Verify NoC Answers to include
  build.gradle
  src/functionalTest/resources/features/common/mca/snippets/NoC_Challenge_Questions_Response.td.json
  src/main/java/uk/gov/hmcts/reform/managecase/client/definitionstore/model/ChallengeQuestion.java
  src/main/java/uk/gov/hmcts/reform/managecase/service/noc/ChallengeAnswerValidator.java
  src/test/java/uk/gov/hmcts/reform/managecase/service/noc/ChallengeAnswerValidatorTest.java
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-443

#448 CCD-3734 - FT issues fixed
  src/functionalTest/resources/features/F-205 - Validate NoC Questions/F-205.feature
  src/functionalTest/resources/features/common/mca/snippets/NoC_Challenge_Questions_Response.td.json
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-448

#446 CCD-3918 CVE-2022-42252
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-446

#452 CCD-3987: Remove case security classification from search API calls.
  src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201_Prerequisite_Case_Creation_C1.td.json
  src/functionalTest/resources/features/F-202 - Get Assignments in My Organisation/F-202_Prerequisite_Case_Creation_C1.td.json
  src/functionalTest/resources/features/F-202 - Get Assignments in My Organisation/F-202_Prerequisite_Case_Creation_C2.td.json
  src/functionalTest/resources/features/F-202 - Get Assignments in My Organisation/F-202_Prerequisite_Case_Creation_C3.td.json
  src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203_Prerequisite_Case_Creation_C1.td.json
  src/functionalTest/resources/features/F-206 - Request Notice Of Change/common/case-creation/FT_NoCAutoApprovalCaseType/F-206_NoC_Auto_Approval_Case_Creation__Base.td.json
  src/functionalTest/resources/features/F-206 - Request Notice Of Change/common/case-creation/FT_NoCCaseType/F-206_NoC_Case_Creation_By_Richard_With_Only_2_Out_Of_3_Org_Policies.td.json
  src/functionalTest/resources/features/F-209 - Apply NoC Decision/SearchCase/F_209_Search_Case_response_data_base.td.json
  src/functionalTest/resources/features/common/data-store/Case_Creation.td.json
  src/functionalTest/resources/features/common/data-store/Case_Creation_Token_Creation.td.json
  src/functionalTest/resources/features/common/data-store/Event_Creation_Token_Creation.td.json
  src/functionalTest/resources/features/common/data-store/FT_NoCAutoApprovalCaseType/NoC_Auto_Approval_Case_Creation_With_Org_Policies__Base.td.json
  src/functionalTest/resources/features/common/data-store/FT_NoCCaseType/NoC_Case_Creation_With_Org_Policies__Base.td.json
  src/functionalTest/resources/features/common/data-store/FT_NoCCaseType/NoC_Case_Creation__Base.td.json
  src/functionalTest/resources/features/common/data-store/FT_NoCWithoutEventsCaseType/NoC_WithoutEvents_Case_Creation_With_Org_Policies__Base.td.json
  src/functionalTest/resources/features/common/data-store/Prerequisite_Case_Creation_C0_Without_Org_Policies.td.json
  src/functionalTest/resources/features/common/data-store/snippets/Data_Store_Audit_Event__Base.td.json
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-452

#437 CCD-3533 Add suppressCves task
  .github/workflows/dependency-check.yml
  build.gradle
  gradle/suppress.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-437

#449 CCD 3734
  build.gradle
  src/functionalTest/resources/features/F-205 - Validate NoC Questions/F-205.feature
  src/functionalTest/resources/features/common/mca/snippets/NoC_Challenge_Questions_Response.td.json
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-449

#444 CCD-3760 CCD-3771 introduce CreatedBy
  src/functionalTest/resources/features/F-206 - Request Notice Of Change/common/verify-case-data/F-206_Verify_Case_Data_COR_Pending.td.json
  src/functionalTest/resources/features/F-208 - Set Organisation To Remove/S-208.1.td.json
  src/functionalTest/resources/features/F-209 - Apply NoC Decision/OrgPolicies/request/F-209_ChangeOrg_Request_data.td.json
  src/functionalTest/resources/features/F-209 - Apply NoC Decision/OrgPolicies/response/F-209_orgPolicy_response_data.td.json
  src/functionalTest/resources/features/F-209 - Apply NoC Decision/OrgPolicies/response/F-209_orgPolicy_response_data_no_previous_org.td.json
  src/functionalTest/resources/features/F-209 - Apply NoC Decision/S-209.4.td.json
  src/functionalTest/resources/features/F-209 - Apply NoC Decision/S-209.5.td.json
  src/functionalTest/resources/features/F-209 - Apply NoC Decision/S-209.8.td.json
  src/functionalTest/resources/features/F-209 - Apply NoC Decision/S-209.9.td.json
  src/integrationTest/java/uk/gov/hmcts/reform/managecase/api/controller/NoticeOfChangeControllerIT.java
  src/main/java/uk/gov/hmcts/reform/managecase/client/datastore/CaseDetails.java
  src/main/java/uk/gov/hmcts/reform/managecase/domain/ChangeOrganisationRequest.java
  src/main/java/uk/gov/hmcts/reform/managecase/domain/OrganisationPolicy.java
  src/main/java/uk/gov/hmcts/reform/managecase/service/noc/ApplyNoCDecisionService.java
  src/main/java/uk/gov/hmcts/reform/managecase/service/noc/RequestNoticeOfChangeService.java
  src/test/java/uk/gov/hmcts/reform/managecase/api/controller/NoticeOfChangeControllerTest.java
  src/test/java/uk/gov/hmcts/reform/managecase/client/datastore/model/CaseDetailsTest.java
  src/test/java/uk/gov/hmcts/reform/managecase/service/noc/ApplyNoCDecisionServiceTest.java
  src/test/java/uk/gov/hmcts/reform/managecase/service/noc/RequestNoticeOfChangeServiceTest.java
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-444

#453 CCD-3916 Update Github actions in workflow
  .github/workflows/scheduled-dummy-commit.yml
  .github/workflows/swagger.yml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-453
