Repository hmcts/aac-manage-case-assignment, pull requests merged in 2022-06, with the labels that each got.

#396 CCD-3297: Added junit formatter to smoke and functional test tasks
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-396

#395 CCD-3261 Fortify Issue 24259118 - Dockerfile Misconfiguration: Defaul…
  Dockerfile
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-395

#397 Revert "CCD-3297: Added junit formatter to smoke and functional test tasks"
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-397

#399 CCD-3387 CVE Suppress Until Date from All Services
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-399
