Repository hmcts/aac-manage-case-assignment, pull requests merged in 2022-07, with the labels that each got.

#405 CCD-3446 : Update suppressions.xml (CVE-2022-33915)
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-405

#407 CCD-3446: CVE-2022-33915 aac-manage-case-assignment
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-407

#408 CCD-3434 upgrade java, postgresql and redis configurations
  charts/aac-manage-case-assignment/Chart.yaml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-408

#374 CCD-2496 Update all repos with multi arch base images
  Dockerfile
  acb.tpl.yaml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-374

#411 CCD-3536: CVE-2022-31569 suppress
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-411

#418 CCD-3518 CVE-2021-22053 suppression removed
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-418

#416 CCD-3561 Upgrade Java and Node JS versions in chart for all the respe…
  charts/aac-manage-case-assignment/Chart.yaml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-416

#422 CCD-3566: Whitelist private law services in test environments (application.yaml, values.yaml, preview.yaml)
  charts/aac-manage-case-assignment/Chart.yaml
  charts/aac-manage-case-assignment/values.preview.template.yaml
  charts/aac-manage-case-assignment/values.yaml
  src/main/resources/application.yaml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-422

#410 CCD-3504 Upgrade to latest java plugin - java plugin upgraded to 0.12…
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/managecase/util/JacksonUtils.java
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-410
