Repository hmcts/aac-manage-case-assignment, pull requests merged in 2022-12, with the labels that each got.

#456 CCD-4043 Fasterxml Jackson Upgrade
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-456

#458 CCD-4090 Functional Test Failures due to Test Definition Failures - I…
  src/functionalTest/resources/features/F-204 - Get NoC Questions/F-204.feature
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-458

#355 added a new bean for CloseableHttpClient to override default timeout …
  src/main/java/uk/gov/hmcts/reform/managecase/config/RestTemplateConfiguration.java
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-355

#461 CCD-4017 Upgrade base charts for Jenkins enhancements - bumped java v…
  charts/aac-manage-case-assignment/Chart.yaml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-461

#457 CCD-4050: Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-457
