Repository hmcts/aac-manage-case-assignment, pull requests merged in 2022-09, with the labels that each got.

#432 Suppress CVE-2022-25857 in suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-432

#431 CCD-3577 cleanup CVE suppressions
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-431

#435 CCD-3682 Suppressions for snakeyaml CVE-2022-38751 CVE-2022-38750 CVE…
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-435

#433 CCD-3426 CVE-2022-34305 tomcat upgrade 9.0.65, suppression removed
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-433

#426 CCD-3509 CVE-2021-22044 spring-cloud-dependencies upgraded 2021.0.3, …
  aca-docker/compose/aca.yml
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/integrationTest/java/uk/gov/hmcts/reform/managecase/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/managecase/config/RestTemplateConfigurationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/managecase/config/SwaggerConfigurationTest.java
  src/main/java/uk/gov/hmcts/reform/managecase/Application.java
  src/main/java/uk/gov/hmcts/reform/managecase/api/payload/AboutToStartCallbackRequest.java
  src/main/java/uk/gov/hmcts/reform/managecase/api/payload/CallbackRequest.java
  src/main/java/uk/gov/hmcts/reform/managecase/api/payload/RequestNoticeOfChangeRequest.java
  src/main/java/uk/gov/hmcts/reform/managecase/api/payload/RequestedCaseUnassignment.java
  src/main/java/uk/gov/hmcts/reform/managecase/api/payload/VerifyNoCAnswersRequest.java
  src/main/java/uk/gov/hmcts/reform/managecase/client/datastore/CaseDetails.java
  src/main/java/uk/gov/hmcts/reform/managecase/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/managecase/config/ZuulConfiguration.java
  src/main/java/uk/gov/hmcts/reform/managecase/domain/SubmittedChallengeAnswer.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/managecase/AdditionalTestOfLombokAnnotationsTest.java
  src/test/java/uk/gov/hmcts/reform/managecase/api/controller/CaseAssignmentControllerTest.java
  src/test/java/uk/gov/hmcts/reform/managecase/api/controller/NoticeOfChangeControllerTest.java
  src/test/java/uk/gov/hmcts/reform/managecase/client/prd/PrdFeignClientTest.java
  src/test/java/uk/gov/hmcts/reform/managecase/repository/DataStoreRepositoryTest.java
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-426

#414 CCD-3539: Stop running Nightly builds on weekends
  Jenkinsfile_nightly
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-414

#420 Remove version number
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-420

#438 CCD-3736: Suppress CVE-2022-38752
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-438
