Repository hmcts/aac-manage-case-assignment, pull requests merged in 2022-04, with the labels that each got.

#378 --Added suppression for Spring beans jar. This is temporary fix.
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-378

#377 spring shell version update to 5.3.18
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-377

#381 jackson.version update for CVE-2020-36518
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-381

#382 New Dates
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-382

#383 Spring-core-5.3.18.jar related suppression
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-383

#370 CWE-862
  build.gradle
  config/owasp/suppressions.xml
  src/integrationTest/resources/wiremock-stubs/idam/oauth-jwk-set.json
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-370
