Repository hmcts/aac-manage-case-assignment, pull requests merged in 2022-10, with the labels that each got.

#434 CCD 3658 CVE 2022 25857 fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-434

#440 Added CVE suppression
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-440

#439 CCD-3773 Conditionally cleanup helm releases on PRs
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-439, keep-helm

#441 CCD-3776 CVE-2022-42003 CVE-2022-42004 jackson version upgraded to 2.…
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-441
