Repository hmcts/aac-manage-case-assignment, pull requests merged in 2023-05, with the labels that each got.

#488 Manage case whitelist ET Callbacks API
  Jenkinsfile_CNP
  charts/aac-manage-case-assignment/Chart.yaml
  charts/aac-manage-case-assignment/values.yaml
  src/main/resources/application.yaml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-488

#490 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-490

#494 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-494
