Repository hmcts/aac-manage-case-assignment, pull requests merged in 2023-01, with the labels that each got.

#465 CCD-4157: Suppress CVE
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-465

#467 Fix pact issue
  Jenkinsfile_CNP
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-467

#450 CCD-3830: Add Gradle runRemoteDemo() task
  .gitignore
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-450

#463 CCD-4035 PATCH to existing PR #455
  Jenkinsfile_CNP
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-463

#455 CCD-4035 - PR to enable ignored FTS
  Jenkinsfile_CNP
  aca-docker/bin/env_variables_all.txt
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/managecase/befta/ManageCaseAssignmentTestAutomationAdapter.java
  src/functionalTest/resources/features/F-204 - Get NoC Questions/F-204.feature
  src/functionalTest/resources/features/F-205 - Validate NoC Questions/F-205.feature
  src/functionalTest/resources/features/F-206 - Request Notice Of Change/F-206 - Request Notice Of Change.feature
  src/functionalTest/resources/features/F-206 - Request Notice Of Change/common/verify-case-data/F-206_Verify_Case_Data_COR_Approved__Base.td.json
  src/functionalTest/resources/features/F-207 - Check Notice Of Change Approval/F-207 - Check Notice Of Change Approval.feature
  src/functionalTest/resources/features/F-207 - Check Notice Of Change Approval/common/F-207_Check_NoC_Auto_Approval_Case_Creation__Base.td.json
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-455

#466 CCD-4163 Bump rse-gradle-java-plugin version
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-466

#472 bump java chart to 4.0.9
  charts/aac-manage-case-assignment/Chart.yaml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-472

#477 CCD-4283: Bump gradle-java-plugin to 0.12.40
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-477
