Repository hmcts/aac-manage-case-assignment, pull requests merged in 2023-02, with the labels that each got.

#478 CCD-4046
  Jenkinsfile_CNP
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-478

#479 CCD-4313: CVE cleanup
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-479

#480 CCD-4312 CVE-2022-45143 Tomcat Upgrade
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-480

#482 CCD-4317 Upgrade base charts
  charts/aac-manage-case-assignment/Chart.yaml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-482
