Repository hmcts/aac-manage-case-assignment, pull requests merged in 2023-03, with the labels that each got.

#483 CCD-4396: Update .terraform-version
  infrastructure/.terraform-version
Labels: ns:aac, prd:aac, add-or-update, rel:aac-manage-case-assignment-pr-483

#484 update befta-fw version to 8.7.11
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-484

#487 CCD-4476 : changed reform-api-docs to cnp-api-docs
  .github/workflows/swagger.yml
  .travis.yml
  README.md
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-487
