Repository hmcts/aac-manage-case-assignment, pull requests merged in 2023-10, with the labels that each got.

#501 Clean up old MI from code
  Jenkinsfile_CNP
  build.gradle
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:aac, prd:aac, destroy, rel:aac-manage-case-assignment-pr-501

#473 CCD-4214 Remove discoveryComposite from health endpoint
  src/functionalTest/resources/features/F-200/S-200.1.td.json
  src/integrationTest/resources/integration-test.properties
  src/main/resources/application.yaml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-473, add-or-update, enable_keep_helm

#503 Add managed identity access for services in aac aat key vault
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:aac, prd:aac, add-or-update, rel:aac-manage-case-assignment-pr-503

#505 CCD-4949:Fix - Versions below java-logging: 6.0.1
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-505

#509 CCD-4943: Update Helm release java to v5
  charts/aac-manage-case-assignment/Chart.yaml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-509
