Repository hmcts/aac-manage-case-assignment, pull requests merged in 2023-11, with the labels that each got.

#510 add fpl to manage identities access
  infrastructure/aat.tfvars
Labels: ns:aac, prd:aac, add-or-update, rel:aac-manage-case-assignment-pr-510

#486 CCD-4454 : CVE-2022-1471-Fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-486

#507 CCD-4771 : Fix CVE-2023-35116
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-507

#506 CCD-4970 : Fix CVE-2020-8908
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-506
