Repository hmcts/aac-manage-case-assignment, pull requests merged in 2024-08, with the labels that each got.

#542 enable fortify failure
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-542

#545 CCD-5194:
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-545

#546 Revert "CCD-5194:"
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-546
