Repository hmcts/aac-manage-case-assignment, pull requests merged in 2024-02, with the labels that each got.

#511 CCD-5045 : Add retries to all acb.tpl.yaml entries
  acb.tpl.yaml
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-511

#525 Update terraform version to fix "There is no function named 'strcontains'" issue
  infrastructure/.terraform-version
  src/functionalTest/resources/features/common/prd/Get_Organisation_Identifier__Base.td.json
Labels: ns:aac, prd:aac, add-or-update, rel:aac-manage-case-assignment-pr-525

#516 Fix CVE-2023-20863
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-516

#523 Fix Pact verification publishing
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-523

#520 CVE fixes 220124
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-520
