Repository hmcts/aac-manage-case-assignment, pull requests merged in 2024-01, with the labels that each got.

#514 DTSPO-15909 - migrated Application Insights
  infrastructure/main.tf
Labels: ns:aac, prd:aac, add-or-update, rel:aac-manage-case-assignment-pr-514

#515 Fix CVE-2023-20861 and CVE-2023-20860
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-515

#513 Updating suppression and bumping minor version
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-513

#518 CVE fixes 160124
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-518
