Repository hmcts/aac-manage-case-assignment, pull requests merged in 2025-01, with the labels that each got.

#554 CCD-4975:
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-554

#555 CME-306: Update azurerm
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:aac, prd:aac, aat/no-changes, prod/no-changes, rel:aac-manage-case-assignment-pr-555

#556 CCD-6049 : Bump ccd-test-definitions and befta-fw to latest
  build.gradle
Labels: ns:aac, prd:aac

#541 CCD-4373
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-541
