Repository hmcts/aac-manage-case-assignment, pull requests merged in 2025-06, with the labels that each got.

#579 CCD-6489 :: suppress CVE 2024 22259
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-579

#572 CME-514 Created new action 'Trigger ADO Artifact Build'
  build.gradle
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-572

#582 CCD-6507 :: Suppress CVE-2024-38808
  config/owasp/suppressions.xml
Labels: ns:aac, prd:aac, rel:aac-manage-case-assignment-pr-582
